homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: !secret unit_system
  time_zone: !secret time_zone
  customize: !include customizations.yaml

frontend:

config:

logger:
  default: debug

#emulated_hue:
#  listen_port: 80

http:
  api_password: !secret http_password

media_player:
  - platform: cast

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac: 34CE008DC4C6
      key: D835A86AD9954A0A
 

updater:
  include_used_components: true

discovery:
conversation:
history:
logbook:
sun:

mqtt: !include mqtt.yaml
switch: !include switches.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml

tts:
  platform: google

group: !include groups.yaml
automation: !include automations.yaml

script: !include_dir_named scripts
