- platform: mqtt
  name: "Master Bathroom Fan Switch"
  command_topic: "devices/246121ef/bathroom-fan/on/set"
  state_topic: "devices/246121ef/bathroom-fan/relay"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  retain: true


- platform: mqtt
  name: "Outdoor Light Switch"
  command_topic: "devices/ab8a62e0/outdoor-light-switch/on/set"
  state_topic: "devices/ab8a62e0/outdoor-light-switch/relay"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  retain: true

